server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:test;LOCK_TIMEOUT=100;
  jpa:
    show-sql: true
    database: h2
  data:
    rest:
      base-path: /api/rest/v1
      detection-strategy: annotated
dozer:
  mapping-files:
  - classpath:dozer/security/person.dozer.xml    
  - classpath:dozer/employee/employee.dozer.xml  